language: python
python:
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script: make travis
notifications:
  email:
    - hylang-discuss@googlegroups.com
  irc:
    channels:
      - "irc.freenode.net#hy"
    on_success: change
    on_failure: change
    use_notice: false